### ISSUE TITLE
Broken Import  - mltraq.utils.plot 

### ISSUE THREAD

**Issue by tcnichol** [elehcimd/mltraq#84]
`
import mltraq
from mltraq.utils.plot import bar_plot`

This import fails. There does not seem to be a method or file within the src.mltraq.utils.

**Comment by elehcimd** [comment]
@tcnichol I dropped `bar_plot` and missed updating the notebooks, which are not part of the automated tests. Could you please see if its definition as in this notebook works for you? Thank You

https://github.com/elehcimd/mltraq/blob/d80bdcdc8834adf15687e9e60d25b8c9220519ae/notebooks/11%20Tracking%20speed%20-%20Benchmarks%204.ipynb

**Comment by elehcimd** [comment]
The issue seems sorted out, closing.
